BBOX_CNT = 2
BBOX_STRUCT_LEN = 5
BBOX_X_POS = 0
BBOX_Y_POS = 1
BBOX_W_POS = 2
BBOX_H_POS = 3
BBOX_C_POS = 4

CLASSES_DISTR_OFFSET = BBOX_CNT * BBOX_STRUCT_LEN
CLASSES_CNT = 20

INPUT_TENSOR_X = 224
INPUT_TENSOR_Y = 224
INPUT_TENSOR_C = 3

OUTPUT_TENSOR_X = 7
OUTPUT_TENSOR_Y = 7
OUTPUT_TENSOR_C = BBOX_CNT * BBOX_STRUCT_LEN + CLASSES_CNT